# Generated by Django 5.2.1 on 2025-05-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_comment_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('go', 'Golang'), ('cpp', 'C++'), ('html', 'HTML')], max_length=30, verbose_name='Язык'),
        ),
    ]
